Add auto-update

diff --git a/moduloproject b/moduloproject
--- a/moduloproject
+++ b/moduloproject
@@ -1,32 +1,87 @@
 #!/bin/sh
 
+# Script version
+SCRIPT_VERSION="1.0"
+
 # Initialize variables with default values
 mode="importmap"
 interpreter="mri"
 version="latest"
 beta_mode=false
 
+# Function to update the script
+update_script() {
+    local url=$1
+    local force=$2
+    echo "Checking for updates..."
+
+    # Download the new version
+    if curl -s "$url" -o "/tmp/moduloproject_new"; then
+        # Compare versions
+        new_version=$(grep "SCRIPT_VERSION=" "$(which moduloproject)" | cut -d'"' -f2 | grep -v "SCRIPT_VERSION")
+        if [ "$new_version" != "$SCRIPT_VERSION" ]; then
+            if [ "$force" = true ] || [ "$beta_mode" = true -a "$force" = false ]; then
+                read -p "New version $new_version available. Update? (y/n) " -n 1 -r
+                echo
+                if [[ $REPLY =~ ^[Yy]$ ]]; then
+                    echo "Updating script..."
+                    if sudo mv "/tmp/moduloproject_new" "/usr/local/bin/moduloproject" && sudo chmod +x "/usr/local/bin/moduloproject"; then
+                        echo "Update successful. Please run the script again."
+                        exit 0
+                    else
+                        echo "Update failed. Please try again or update manually."
+                        exit 1
+                    fi
+                fi
+            elif [ "$force" = true ]; then
+                echo "Forcing update to version $new_version..."
+                if sudo mv "/tmp/moduloproject_new" "/usr/local/bin/moduloproject" && sudo chmod +x "/usr/local/bin/moduloproject"; then
+                    echo "Forced update successful. Please run the script again."
+                    exit 0
+                else
+                    echo "Forced update failed. Please try again or update manually."
+                    exit 1
+                fi
+            fi
+        else
+            echo "You are already using the latest version."
+        fi
+    else
+        echo "Failed to check for updates."
+    fi
+    rm -f "/tmp/moduloproject_new"
+}
+
 # Help function in English
 show_help() {
-  echo "Usage: moduloproject [-m MODE] [-i INTERPRETER] [-v VERSION] [-b] [-h]"
+  echo "Usage: moduloproject [-m MODE] [-i INTERPRETER] [-v VERSION] [-b] [-u] [-h]"
   echo "  -m MODE         Mode (importmap, esbuild, webpack). Default: importmap"
   echo "  -i INTERPRETER  Interpreter (mri, jruby). Default: mri"
   echo "  -v VERSION      Version. Default: latest"
   echo "  -b              Enable beta mode (uses development branch)"
+  echo "  -u              Force update check"
   echo "  -h              Display this help message"
 }
 
 # Parse options
-while getopts "m:i:v:bh" opt; do
+while getopts "m:i:v:buh" opt; do
   case $opt in
     m) mode=$OPTARG ;;
     i) interpreter=$OPTARG ;;
     v) version=$OPTARG ;;
     b) beta_mode=true ;;
+    u) update_script "https://raw.githubusercontent.com/moduloTech/moduloproject/master/moduloproject" true ;;
     h) show_help; exit 0 ;;
     \?) echo "Invalid option: -$OPTARG" >&2; show_help; exit 1 ;;
   esac
 done
+
+# Check for updates
+if [ "$beta_mode" = true ]; then
+    update_script "https://raw.githubusercontent.com/moduloTech/moduloproject/development/moduloproject" false
+else
+    update_script "https://raw.githubusercontent.com/moduloTech/moduloproject/master/moduloproject" true
+fi
 
 # Validate options
 if [ "$mode" != "importmap" ] && [ "$mode" != "esbuild" ] && [ "$mode" != "webpack" ]; then
@@ -100,7 +155,7 @@ database_url="postgres://postgres:${postgres_password}@${postgres_ip}:5432/postg
 docker run --name moduloproject --pull=always --rm -a STDOUT -ti -w "$docker_project_directory" \
   -v "$local_project_directory":"$docker_project_directory" \
   -e "GIT_AUTHOR_EMAIL=$git_email" -e "GIT_AUTHOR_NAME=$git_name" -e "GIT_COMMITTER_EMAIL=$git_email" -e "GIT_COMMITTER_NAME=$git_name" \
-  -e "JAVASCRIPT_MODE=$mode" -e "EXTRA_RAILS_ARGS=$extra_rails_args" \
+  -e "JAVASCRIPT_MODE=$mode" -e "EXTRA_RAILS_ARGS=$extra_rails_args" -e "MODULORAILS_BETA_MODE=$beta_mode" \
   -e "DATABASE_URL=$database_url" \
   --network host \
   "$image" bash -c "$script"
